FROM postgres

ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG POSTGRES_DB

ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_DB=$POSTGRES_DB

COPY docker/data/model_init.sh /docker-entrypoint-initdb.d/1.sh
COPY docker/data/first_credentials.sql /docker-entrypoint-initdb.d/2.sql
COPY docker/data/docker-entrypoint.sh /usr/local/bin/

RUN apt-get update && apt-get install -y python3 python3-pip

COPY . /app
RUN pip3 install -r /app/requirements.txt

EXPOSE 5432:5432
