FROM python:3.6

ARG HOST
ARG PORT

ENV HOST=$HOST
ENV PORT=$PORT

COPY . /app
WORKDIR /app

RUN pip3 install -r /app/requirements.txt

CMD gunicorn \
--bind ${HOST}:${PORT} \
--log-level "debug" \
--log-file "-" \
-w 8 \
--preload \
runserver:app
