version: '2.1'
services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile-api
      args:
        HOST: 0.0.0.0
        PORT: 5000
    ports:
     - "5000:5000"
    links:
     - db:db
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: ..
      dockerfile: docker/Dockerfile-db
      args:
        POSTGRES_PASSWORD: toor
        POSTGRES_USER: root
        POSTGRES_DB: todo
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
     build:
       context: ..
       dockerfile: docker/Dockerfile-tests
     tty: true
     stdin_open: true
     links:
       - api:api

